# Generated by Django 3.2 on 2021-12-11 16:42

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='chat',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'Игра', 'verbose_name_plural': 'Игры'},
        ),
        migrations.AlterModelOptions(
            name='gameparticipant',
            options={'verbose_name': 'Участник игры', 'verbose_name_plural': 'Участники игры'},
        ),
        migrations.AlterModelOptions(
            name='gameplayer',
            options={'verbose_name': 'Игрок', 'verbose_name_plural': 'Игроки'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задание', 'verbose_name_plural': 'Задания'},
        ),
        migrations.AlterModelOptions(
            name='template',
            options={'verbose_name': 'Шаблон', 'verbose_name_plural': 'Шаблоны'},
        ),
        migrations.AlterModelManagers(
            name='botuser',
            managers=[
                ('users', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='chat',
            managers=[
                ('chats', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='game',
            managers=[
                ('games', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='gameparticipant',
            managers=[
                ('participants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='gameplayer',
            managers=[
                ('players', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='task',
            managers=[
                ('tasks', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='botuser',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='lang',
            field=models.CharField(choices=[('ru', 'Ru'), ('en', 'En')], max_length=2, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='last_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='username',
            field=models.CharField(max_length=255, null=True, verbose_name='Ник'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='lang',
            field=models.CharField(choices=[('ru', 'Ru'), ('en', 'En')], max_length=2, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='game',
            name='chat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='backend.chat', verbose_name='Игра'),
        ),
        migrations.AlterField(
            model_name='gameparticipant',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='backend.game', verbose_name='Игра'),
        ),
        migrations.AlterField(
            model_name='gameparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='backend.botuser', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='gameplayer',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='backend.game', verbose_name='Игра'),
        ),
        migrations.AlterField(
            model_name='gameplayer',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='backend.task', verbose_name='Задание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='body',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.IntegerField(choices=[(1, 'Правда'), (2, 'Действие')], verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='template',
            name='body_en',
            field=models.TextField(verbose_name='На английском'),
        ),
        migrations.AlterField(
            model_name='template',
            name='body_ru',
            field=models.TextField(verbose_name='На русском'),
        ),
        migrations.AlterField(
            model_name='template',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='template',
            name='type',
            field=models.IntegerField(choices=[(1, 'Message'), (2, 'Key'), (3, 'Smile')], verbose_name='Тип'),
        ),
    ]
