# Generated by Django 3.2 on 2021-12-11 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_gameplayer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameplayer',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='backend.task', verbose_name='Задание'),
        ),
    ]
