# Generated by Django 3.2 on 2021-12-15 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_game_current_player'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gameplayer',
            unique_together={('user', 'game')},
        ),
    ]
