# Generated by Django 3.2 on 2021-12-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_gameplayer_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='body',
        ),
        migrations.AddField(
            model_name='task',
            name='body_en',
            field=models.TextField(default='', verbose_name='Текст на английском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='body_ru',
            field=models.TextField(default='', verbose_name='Текст на русском'),
            preserve_default=False,
        ),
    ]
