# Generated by Django 3.2 on 2021-12-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20211215_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='message_id',
            field=models.IntegerField(null=True),
        ),
    ]
